# Generated by Django 4.2.5 on 2023-10-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reggg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
